# Generated by Django 5.0.3 on 2024-07-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('album_id', models.IntegerField()),
                ('album_name', models.CharField(max_length=35)),
                ('album_elements', models.IntegerField()),
                ('creationdate', models.DateTimeField()),
                ('lastupdate', models.DateTimeField()),
                ('cover', models.IntegerField(null=True)),
                ('is_owner', models.BooleanField()),
                ('permissions', models.CharField(max_length=15, null=True)),
                ('code', models.CharField(max_length=8, null=True)),
            ],
            options={
                'db_table': '"public"."user_albums_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"public"."user_data_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('album_id', models.IntegerField()),
                ('album_name', models.CharField(max_length=35)),
                ('media_id', models.IntegerField()),
                ('is_cover', models.BooleanField()),
                ('filename', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=20)),
                ('modificationdate', models.DateTimeField()),
                ('coordinates', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('label', models.CharField(max_length=50, null=True)),
                ('detectedobjects', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"public"."user_media_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('lastupdate', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8, null=True, unique=True)),
                ('permissions', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': '"public"."album"',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('modificationdate', models.DateTimeField()),
                ('kind', models.CharField(max_length=20)),
                ('coordinates', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('label', models.CharField(max_length=50, null=True)),
                ('detectedobjects', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"public"."media"',
            },
        ),
        migrations.CreateModel(
            name='AlbumUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"public"."album_user"',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ManyToManyField(through='core.AlbumUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_cover', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.media')),
            ],
            options={
                'db_table': '"public"."media_album"',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='album',
            field=models.ManyToManyField(through='core.MediaAlbum', to='core.album'),
        ),
    ]
