# Generated by Django 5.0.3 on 2024-07-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_views'),
    ]

    operations = [
        # Make auth_user email unique
        migrations.RunSQL('''
            ALTER TABLE auth_user
            ADD CONSTRAINT auth_user_email_key UNIQUE (email);
        '''),
    ]
