services:
  db:
    build: ./db
    environment:
      - POSTGRES_DB=galeria
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 10s
      retries: 5
    container_name: galeria-db
    volumes:
      # Backup database directory
      - ./db/backups:/backups

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    container_name: galeria-app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  server:
    build: ./server
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    container_name: galeria-server

networks:
  default:
    name: galeria-prod
